# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BJmknXsnC-azIBCYavV4ta2edCk5Bgfr
"""

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
import pandas as pd
import time
from datetime import date
import numpy as np
import pandas as pd
import plotly.express as px
from scipy import stats
import os.path
from datetime import date, timedelta
def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days)):
        yield start_date + timedelta(n)

nav = webdriver.Chrome()

tempo = 1
time.sleep(tempo)
nav.get("https://www.aduaneiras.com.br/Informacoes/Taxas")
time.sleep(tempo)

df = pd.DataFrame({ "data":[],
                    "USD-220":[], 
                    "EUR-978":[],
                    "IENE-470":[],
                    "NOK-065":[],
                    "DKK-055":[],
                    "GBP-540":[],
                  })

time.sleep(tempo)
nav.find_element_by_xpath('/html/body/div[2]/div[7]/div[1]/div/input').clear()

single_date = date(2016, 1, 1)

count = 1
pagina = 1
while count <= 2:
    nav.find_element_by_xpath('/html/body/div[2]/div[7]/div[1]/div/input').send_keys(single_date.strftime("%d/%m/%Y"))
    nav.find_element_by_xpath('/html/body/div[2]/div[7]/div[1]/div/input').send_keys(Keys.ENTER)
    time.sleep(tempo)
    usd = nav.find_element_by_xpath('/html/body/div[2]/div[7]/div[2]/table/tbody/tr[53]/td[3]').text
    eur = nav.find_element_by_xpath('/html/body/div[2]/div[7]/div[2]/table/tbody/tr[55]/td[3]').text
    iene = nav.find_element_by_xpath('/html/body/div[2]/div[7]/div[2]/table/tbody/tr[72]/td[3]').text
    nok = nav.find_element_by_xpath('/html/body/div[2]/div[7]/div[2]/table/tbody/tr[12]/td[3]').text
    dkk = nav.find_element_by_xpath('/html/body/div[2]/div[7]/div[2]/table/tbody/tr[10]/td[3]').text
    gbp = nav.find_element_by_xpath('/html/body/div[2]/div[7]/div[2]/table/tbody/tr[84]/td[3]').text
    print(single_date.strftime("%d/%m/%Y"), " - ", usd, " - ", eur, iene, nok, dkk, gbp)
    newrow = {"data":single_date.strftime("%d/%m/%Y"), "USD-220":usd, "EUR-978":eur, "IENE-470":iene, "NOK-065":nok, "DKK-055":dkk, "GBP-540":gbp }
    df = df.append(newrow, ignore_index=True)
    count += 1
    single_date = single_date + timedelta(days=1)
    nav.find_element_by_xpath('/html/body/div[2]/div[7]/div[1]/div/input').clear()

print(single_date)

df.to_csv('out.csv', sep=',', encoding='utf-8')

